function [frame, rightFhoof, rightFhoof1, rightFhoof2, rightHhoof, rightHhoof1, rightHhoof2, righthock, righthock1, righthock2, rightFfetlock, rightFfetlock1, rightFfetlock2, rightHfetlock, rightHfetlock1, rightHfetlock2, rightknee, rightknee1, rightknee2, handlerRfoot, handlerRfoot1, handlerRfoot2, handlerRknee, handlerRknee1, handlerRknee2, nostril, nostril1, nostril2, poll, poll1, poll2, withers, withers1, withers2, shoulder, shoulder1, shoulder2, elbow, elbow1, elbow2, croup, croup1, croup2, hip, hip1, hip2, stifle, stifle1, stifle2, pointofbuttock, pointofbuttock1, pointofbuttock2, leftFhoof, leftFhoof1, leftFhoof2, leftHhoof, leftHhoof1, leftHhoof2, lefthock, lefthock1, lefthock2, leftFfetlock, leftFfetlock1, leftFfetlock2, leftHfetlock, leftHfetlock1, leftHfetlock2, leftknee, leftknee1, leftknee2, handlerLfoot, handlerLfoot1, handlerLfoot2, handlerLknee, handlerLknee1, handlerLknee2] = import_horse(filename, dataLines)

%IMPORTFILE Import data from a text file
%  [BODYPARTS, RIGHTFHOOF, RIGHTFHOOF1, RIGHTFHOOF2, RIGHTHHOOF,
%  RIGHTHHOOF1, RIGHTHHOOF2, RIGHTHOCK, RIGHTHOCK1, RIGHTHOCK2,
%  RIGHTFFETLOCK, RIGHTFFETLOCK1, RIGHTFFETLOCK2, RIGHTHFETLOCK,
%  RIGHTHFETLOCK1, RIGHTHFETLOCK2, RIGHTKNEE, RIGHTKNEE1, RIGHTKNEE2,
%  HANDLERRFOOT, HANDLERRFOOT1, HANDLERRFOOT2, HANDLERRKNEE,
%  HANDLERRKNEE1, HANDLERRKNEE2, NOSTRIL, NOSTRIL1, NOSTRIL2, POLL,
%  POLL1, POLL2, WITHERS, WITHERS1, WITHERS2, SHOULDER, SHOULDER1,
%  SHOULDER2, ELBOW, ELBOW1, ELBOW2, CROUP, CROUP1, CROUP2, HIP, HIP1,
%  HIP2, STIFLE, STIFLE1, STIFLE2, POINTOFBUTTOCK, POINTOFBUTTOCK1,
%  POINTOFBUTTOCK2, LEFTFHOOF, LEFTFHOOF1, LEFTFHOOF2, LEFTHHOOF,
%  LEFTHHOOF1, LEFTHHOOF2, LEFTHOCK, LEFTHOCK1, LEFTHOCK2, LEFTFFETLOCK,
%  LEFTFFETLOCK1, LEFTFFETLOCK2, LEFTHFETLOCK, LEFTHFETLOCK1,
%  LEFTHFETLOCK2, LEFTKNEE, LEFTKNEE1, LEFTKNEE2, HANDLERLFOOT,
%  HANDLERLFOOT1, HANDLERLFOOT2, HANDLERLKNEE, HANDLERLKNEE1,
%  HANDLERLKNEE2] = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as column
%  vectors.
%
%  [BODYPARTS, RIGHTFHOOF, RIGHTFHOOF1, RIGHTFHOOF2, RIGHTHHOOF,
%  RIGHTHHOOF1, RIGHTHHOOF2, RIGHTHOCK, RIGHTHOCK1, RIGHTHOCK2,
%  RIGHTFFETLOCK, RIGHTFFETLOCK1, RIGHTFFETLOCK2, RIGHTHFETLOCK,
%  RIGHTHFETLOCK1, RIGHTHFETLOCK2, RIGHTKNEE, RIGHTKNEE1, RIGHTKNEE2,
%  HANDLERRFOOT, HANDLERRFOOT1, HANDLERRFOOT2, HANDLERRKNEE,
%  HANDLERRKNEE1, HANDLERRKNEE2, NOSTRIL, NOSTRIL1, NOSTRIL2, POLL,
%  POLL1, POLL2, WITHERS, WITHERS1, WITHERS2, SHOULDER, SHOULDER1,
%  SHOULDER2, ELBOW, ELBOW1, ELBOW2, CROUP, CROUP1, CROUP2, HIP, HIP1,
%  HIP2, STIFLE, STIFLE1, STIFLE2, POINTOFBUTTOCK, POINTOFBUTTOCK1,
%  POINTOFBUTTOCK2, LEFTFHOOF, LEFTFHOOF1, LEFTFHOOF2, LEFTHHOOF,
%  LEFTHHOOF1, LEFTHHOOF2, LEFTHOCK, LEFTHOCK1, LEFTHOCK2, LEFTFFETLOCK,
%  LEFTFFETLOCK1, LEFTFFETLOCK2, LEFTHFETLOCK, LEFTHFETLOCK1,
%  LEFTHFETLOCK2, LEFTKNEE, LEFTKNEE1, LEFTKNEE2, HANDLERLFOOT,
%  HANDLERLFOOT1, HANDLERLFOOT2, HANDLERLKNEE, HANDLERLKNEE1,
%  HANDLERLKNEE2] = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  [bodyparts, rightFhoof, rightFhoof1, rightFhoof2, rightHhoof, rightHhoof1, rightHhoof2, righthock, righthock1, righthock2, rightFfetlock, rightFfetlock1, rightFfetlock2, rightHfetlock, rightHfetlock1, rightHfetlock2, rightknee, rightknee1, rightknee2, handlerRfoot, handlerRfoot1, handlerRfoot2, handlerRknee, handlerRknee1, handlerRknee2, nostril, nostril1, nostril2, poll, poll1, poll2, withers, withers1, withers2, shoulder, shoulder1, shoulder2, elbow, elbow1, elbow2, croup, croup1, croup2, hip, hip1, hip2, stifle, stifle1, stifle2, pointofbuttock, pointofbuttock1, pointofbuttock2, leftFhoof, leftFhoof1, leftFhoof2, leftHhoof, leftHhoof1, leftHhoof2, lefthock, lefthock1, lefthock2, leftFfetlock, leftFfetlock1, leftFfetlock2, leftHfetlock, leftHfetlock1, leftHfetlock2, leftknee, leftknee1, leftknee2, handlerLfoot, handlerLfoot1, handlerLfoot2, handlerLknee, handlerLknee1, handlerLknee2] = importfile("C:\Users\savan\Desktop\horse\bolytairB_LRK_1.csv", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Nov-2021 15:31:21

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 76);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["bodyparts", "rightFhoof", "rightFhoof1", "rightFhoof2", "rightHhoof", "rightHhoof1", "rightHhoof2", "righthock", "righthock1", "righthock2", "rightFfetlock", "rightFfetlock1", "rightFfetlock2", "rightHfetlock", "rightHfetlock1", "rightHfetlock2", "rightknee", "rightknee1", "rightknee2", "handlerRfoot", "handlerRfoot1", "handlerRfoot2", "handlerRknee", "handlerRknee1", "handlerRknee2", "nostril", "nostril1", "nostril2", "poll", "poll1", "poll2", "withers", "withers1", "withers2", "shoulder", "shoulder1", "shoulder2", "elbow", "elbow1", "elbow2", "croup", "croup1", "croup2", "hip", "hip1", "hip2", "stifle", "stifle1", "stifle2", "pointofbuttock", "pointofbuttock1", "pointofbuttock2", "leftFhoof", "leftFhoof1", "leftFhoof2", "leftHhoof", "leftHhoof1", "leftHhoof2", "lefthock", "lefthock1", "lefthock2", "leftFfetlock", "leftFfetlock1", "leftFfetlock2", "leftHfetlock", "leftHfetlock1", "leftHfetlock2", "leftknee", "leftknee1", "leftknee2", "handlerLfoot", "handlerLfoot1", "handlerLfoot2", "handlerLknee", "handlerLknee1", "handlerLknee2"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
frame = tbl.bodyparts;
rightFhoof = tbl.rightFhoof;
rightFhoof1 = tbl.rightFhoof1;
rightFhoof2 = tbl.rightFhoof2;
rightHhoof = tbl.rightHhoof;
rightHhoof1 = tbl.rightHhoof1;
rightHhoof2 = tbl.rightHhoof2;
righthock = tbl.righthock;
righthock1 = tbl.righthock1;
righthock2 = tbl.righthock2;
rightFfetlock = tbl.rightFfetlock;
rightFfetlock1 = tbl.rightFfetlock1;
rightFfetlock2 = tbl.rightFfetlock2;
rightHfetlock = tbl.rightHfetlock;
rightHfetlock1 = tbl.rightHfetlock1;
rightHfetlock2 = tbl.rightHfetlock2;
rightknee = tbl.rightknee;
rightknee1 = tbl.rightknee1;
rightknee2 = tbl.rightknee2;
handlerRfoot = tbl.handlerRfoot;
handlerRfoot1 = tbl.handlerRfoot1;
handlerRfoot2 = tbl.handlerRfoot2;
handlerRknee = tbl.handlerRknee;
handlerRknee1 = tbl.handlerRknee1;
handlerRknee2 = tbl.handlerRknee2;
nostril = tbl.nostril;
nostril1 = tbl.nostril1;
nostril2 = tbl.nostril2;
poll = tbl.poll;
poll1 = tbl.poll1;
poll2 = tbl.poll2;
withers = tbl.withers;
withers1 = tbl.withers1;
withers2 = tbl.withers2;
shoulder = tbl.shoulder;
shoulder1 = tbl.shoulder1;
shoulder2 = tbl.shoulder2;
elbow = tbl.elbow;
elbow1 = tbl.elbow1;
elbow2 = tbl.elbow2;
croup = tbl.croup;
croup1 = tbl.croup1;
croup2 = tbl.croup2;
hip = tbl.hip;
hip1 = tbl.hip1;
hip2 = tbl.hip2;
stifle = tbl.stifle;
stifle1 = tbl.stifle1;
stifle2 = tbl.stifle2;
pointofbuttock = tbl.pointofbuttock;
pointofbuttock1 = tbl.pointofbuttock1;
pointofbuttock2 = tbl.pointofbuttock2;
leftFhoof = tbl.leftFhoof;
leftFhoof1 = tbl.leftFhoof1;
leftFhoof2 = tbl.leftFhoof2;
leftHhoof = tbl.leftHhoof;
leftHhoof1 = tbl.leftHhoof1;
leftHhoof2 = tbl.leftHhoof2;
lefthock = tbl.lefthock;
lefthock1 = tbl.lefthock1;
lefthock2 = tbl.lefthock2;
leftFfetlock = tbl.leftFfetlock;
leftFfetlock1 = tbl.leftFfetlock1;
leftFfetlock2 = tbl.leftFfetlock2;
leftHfetlock = tbl.leftHfetlock;
leftHfetlock1 = tbl.leftHfetlock1;
leftHfetlock2 = tbl.leftHfetlock2;
leftknee = tbl.leftknee;
leftknee1 = tbl.leftknee1;
leftknee2 = tbl.leftknee2;
handlerLfoot = tbl.handlerLfoot;
handlerLfoot1 = tbl.handlerLfoot1;
handlerLfoot2 = tbl.handlerLfoot2;
handlerLknee = tbl.handlerLknee;
handlerLknee1 = tbl.handlerLknee1;
handlerLknee2 = tbl.handlerLknee2;
end